### ISSUE TITLE
Demo with Facial Mocap

### ISSUE THREAD

**Issue by GeorgeS2019** [gdquest-demos/godot-4.0-new-features#34]
There is interest to do Facial or perhaps whole body Mocap using [Godot]
Perhaps someone here could help him?
(https://github.com/SpookyCorgi/phiz/issues/5#issuecomment-1512282598)
![vlc_KO6i29PaZ1](https://user-images.githubusercontent.com/49812372/235353266-21269f31-6656-4c4d-b479-c22af7120cfe.gif)

![msedge_NCsDDUi3om](https://user-images.githubusercontent.com/49812372/235352984-8361e543-7681-45f3-acce-fbe78f1061f4.gif)

**Comment by NathanLovato** [comment]
Hey buddy, this is the Issue tracker for our Godot release video, not a place to request misc. Godot demos for third party integration.  Thanks for your understanding.
